name:                catchallHaskell
version:             0.1.0.0
github:              "githubuser/catchallHaskell"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/catchallHaskell#readme>

dependencies:
- base >= 4.7 && < 5
- split
- containers 
- split
- random
- vector
- universum
- QuickCheck
- utility-ht
- matrix
- array
- sort 
- time 
- hspec
- QuickCheck
- process 
- primes 
- random-shuffle
- checkers
- semigroups
- bytestring
- text
- mtl 
- transformers
- trifecta
- universe-base
- probability
- groupBy
- data-ordlist
- time
- vector 
- lens

library:
  source-dirs: src

executables:
  catchallHaskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - catchallHaskell

tests:
  catchallHaskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - catchallHaskell
